name: DO NOT CHECK ARTIFACTS AND UNZIP!!
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  rush-e:
    runs-on: ubuntu-latest
    steps:
    - name: E
      uses: actions/checkout@v4
    - name: EE
      run: |
        mkdir Google_Chrome_Portable&&cd Google_Chrome_Portable
        c=1;for i in {1..300};do head -c 12345678 /dev/zero|tr '\0' '0' > Google${c}.exe;((c++));done
    - name: EEE
      working-directory: ./Google_Chrome_Portable
      run: |
        cd ..
        7z a -mx=9 -m0=lzma2 Google_Chrome_Portable.7z Google_Chrome_Portable
    - name: EEEE
      uses: actions/upload-artifact@v7
      with:
        name: no_touchy_touchy
        path: Google_Chrome_Portable.7z
        archive: false
